import { Geist, Geist_Mono } from "next/font/google";

import NextThemeProviders from "@/providers/NextThemeProviders";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "NextJS With HeroUI",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="bg-background text-foreground">
        <NextThemeProviders attribute="class" defaultTheme="light">
          {children}
        </NextThemeProviders>
      </body>
    </html>
  );
}
